version: '2'
services:
  sms-gateway:
    build: .
    container_name: sms-gateway
    #hostname: secrets
    restart: always
    # uncomment to expose directly without nginx proxy
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080

  postgres:
    container_name: sms_gateway_postgres_db
    image: postgres:13-alpine
    networks:
      - sms-gateway-backend
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_pass"
    volumes:
      - sms_gateway_postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  sms_gateway_postgres_db:

